- name: play variables
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: print play variables
      ansible.builtin.debug:
        msg: url = {{url}}


- name: play variables from files
  hosts: localhost
  vars_files:
    var.yml
  tasks: print variable from files
  ansible.builtin.debug:
    msg: url= {{url}