- name: play variables
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: print play variables
      ansible.builtin.debug:
        msg: url = {{url}}


- name: play variables from files
  hosts: localhost
  vars_files:
   - var.yml
  tasks:
  - name: print play variables from files
    ansible.builtin.debug:
      msg: url = {{ url }}

- name: task level variables
  hosts: localhost
  tasks:
    - name: print play variables
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: variable from inventory
  hosts: all
  tasks:
    - name: print play variable from inventory
      ansible.builtin.debug:
        msg: "URL = {{ URL }},host name of server = {{ansible_user}}"


